services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.1
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: none  # No vectorizer or configure another module
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: 'node1'
